# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
