# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20171111_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/%Y/%M/%d'),
        ),
    ]
